#!/usr/bin/env python3
"""Regenerate src/mans/pdf_tables.rs from the reference software's ec_lib_mans.py.

Usage: python3 scripts/gen_pdf_tables.py ~/work/zen/jpeg-ai-reference-software > src/mans/pdf_tables.rs
"""
import re
import sys

ref = sys.argv[1]
src = open(f"{ref}/src/codec/entropy_coding/lib_wrappers/mans/ec_lib_mans.py").read()
pdf_r = eval(re.search(r"pdf_r=(\[\[.*?\]\s*\])\s*self\.pdf_r", src, re.S).group(1))
bounds = eval(re.search(r"bound_table_r=(\[.*?\])", src).group(1))
assert len(pdf_r) == len(bounds) == 32
assert all(sum(p) + 1 == 256 for p in pdf_r)

out = [
    "//! Normative residual PDFs for me-tANS, verbatim from the reference software",
    "//! (`ECLibMans.__init__::pdf_r` and `init_quant_params::bound_table_r` in",
    "//! `ref/src/codec/entropy_coding/lib_wrappers/mans/ec_lib_mans.py`).",
    "//!",
    "//! Generated by `scripts/gen_pdf_tables.py`; do not edit by hand.",
    "//!",
    "//! Row `i` is the PDF for quantised-sigma index `i`. Entries are 8-bit masses for the symbols",
    "//! `0, -1, +1, -2, +2, ...` in that order. One extra unit of mass goes to the escape symbol",
    "//! `-bound[i]`, so that every row sums to 256.",
    "",
    "/// Number of residual distributions (`NUM_DISTRIBUTIONS_R`).",
    "pub(crate) const NUM_DISTRIBUTIONS_R: usize = 32;",
    "",
    "/// Symbol bound per distribution: values with `|v| >= bound` are escape-coded.",
    "pub(crate) const BOUND_TABLE_R: [u8; NUM_DISTRIBUTIONS_R] = [" + ", ".join(map(str, bounds)) + "];",
    "",
]
flat, offs = [], [0]
for p in pdf_r:
    flat += p
    offs.append(len(flat))
out += [
    "/// Start offset of each row in [`PDF_R_FLAT`] (one past-the-end entry appended).",
    "pub(crate) const PDF_R_OFFSETS: [u16; NUM_DISTRIBUTIONS_R + 1] = [" + ", ".join(map(str, offs)) + "];",
    "",
    "/// All rows of `pdf_r`, concatenated.",
    f"pub(crate) const PDF_R_FLAT: [u8; {len(flat)}] = [",
]
for i, p in enumerate(pdf_r):
    out.append(f"    // sigma index {i} ({len(p)} symbols, bound {bounds[i]})")
    line = "    "
    for v in p:
        tok = f"{v}, "
        if len(line) + len(tok) > 100:
            out.append(line.rstrip())
            line = "    "
        line += tok
    out.append(line.rstrip())
out.append("];")
print("\n".join(out))
